DZ_L18/users/__init__.py
from flask import Blueprint

users_b = Blueprint('users', __name__, template_folder='templates', static_folder='static')

from users.routes import *

DZ_L18/users/routes.py
from users import users_b
from users.func_bd import authorization, registration
from flask import render_template, request, flash, redirect, url_for
from users.func_valid import validate_email_pass
from flask_login import logout_user


@users_b.route('/registration', methods=["POST", "GET"])
def f_registration():
    errors = []
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        password2 = request.form.get('password2')

        errors.extend(validate_email_pass(email, password, password2))

        if not errors:
            registration(email, password)
            return redirect(url_for('index'))

    return render_template('registration.html', errors=errors)


@users_b.route('/authorization',  methods=["POST", "GET"])
def f_authentication():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        remember_me = request.form.get('remember') == 'on'
        if authorization(email, password, remember_me):
            return redirect(url_for('index'))
        else:
            flash('Неверный email или пароль.')

    return render_template('authentication.html')


@users_b.route('/logout', methods=['POST', 'GET'])
def logout():
    logout_user()
    return redirect(url_for('index'))

DZ_L18/users/templates/authentication.html
{% extends 'index.html' %}

{% block content %}
    {% if get_flashed_messages() %}
        {% for message in get_flashed_messages() %}
            <div class="alert alert-success" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
<div class="container mt-4">
    <div class="list-item-container alert alert-info" role="alert">
        <div class="text-center mb-4">
            <h1>Вход</h1>
            <form action="{{ url_for('users.f_authentication') }}" method="post" class="mt-3">
                <div class="mb-3">
                    <label for="email" class="form-label">Email</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="Введите email" required>
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">Пароль</label>
                    <input type="password" class="form-control" id="password" name="password" placeholder="Введите пароль" required>
                </div>
                <div class="field">
                    <label class="checkbox">
                        <input type="checkbox" name="remember">
                        Запомнить меня
                    </label>
                </div>
                <button type="submit" class="btn btn-primary">Войти</button>
            </form>
        </div>
    <div class="d-flex justify-content-center">
        <a href="{{ url_for('users.f_registration') }}" class="btn btn-secondary mt-auto">Регистрация</a>
    </div>
    </div>
</div>
{% endblock %}

DZ_L18/users/templates/registration.html
{% extends 'index.html' %}

{% block content %}
    {% for error in errors %}
        <div class="alert alert-success" role="alert">
            {{ error }}
        </div>
    {% endfor %}
<div class="container mt-4">
    <div class="list-item-container alert alert-info" role="alert">
        <div class="text-center mb-4">
            <h1>Регистрация</h1>
            <form action="{{ url_for('users.f_registration') }}" method="post" class="mt-3">
                <div class="mb-3">
                    <label for="email" class="form-label">Email</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="Введите email" required>
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">Пароль</label>
                    <input type="password" class="form-control" id="password" name="password" placeholder="Создайте пароль" required>
                </div>
                <div class="mb-3">
                    <label for="password2" class="form-label">Подтверждение пароля</label>
                    <input type="password" class="form-control" id="password2" name="password2" placeholder="Повторите пароль" required>
                </div>
                <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
            </form>
        </div>
    <div class="d-flex justify-content-center">
        <a href="{{ url_for('users.f_authentication') }}" class="btn btn-secondary mt-auto">Назад</a>
    </div>
    </div>
</div>
{% endblock %}