DZ_L18/books/__init__.py
from flask import Blueprint

books_b = Blueprint('books', __name__, template_folder='templates')

from books.routes import *

DZ_L18/books/routes.py
from books import books_b
from books.func_bd import (show_books, add_book, update_book, delete_book,
                           find_book, show_my_books, add_my_book, delete_my_book)
from flask import render_template, request, flash, redirect, url_for
from flask_login import current_user
from users.login_required import login_required


@books_b.route('/books')
def books():
    return render_template('books.html')


@books_b.route('/show_books')
def f_show_books():
    books = show_books()
    return render_template('show_books.html', books=books)


@books_b.route('/show_book/<int:book_id>')
def f_show_book(book_id):
    books = show_books()
    current_book = None
    prev_book_id = None
    next_book_id = None

    for i, book in enumerate(books):
        if book.id == book_id:
            current_book = book
            if i > 0:
                prev_book_id = books[i-1].id
            if i < len(books) - 1:
                next_book_id = books[i+1].id
            break

    if current_book:
        return render_template('show_book.html', book=current_book,
                               prev_book_id=prev_book_id, next_book_id=next_book_id)
    else:
        return 'Книга не найдена', 404


@books_b.route('/add_book', methods=["POST", "GET"])
def f_add_book():
    name = None
    author_id = None
    from authors.func_bd import show_authors
    authors = show_authors()

    if request.method == 'POST':
        len_authors = len(show_authors())
        author_id = int(request.form['author_id'])
        if len_authors >= author_id:
            name = request.form['name']
            add_book(name, author_id)
            flash('Книга успешно добавлена', 'success')
        else:
            flash('Ошибка добавления книги. Проверьте данные.', 'error')
    return render_template('add_book.html', name=name, author_id=author_id, authors=authors)


@books_b.route('/update_book', methods=["POST", "GET"])
def f_update_book():
    new_name = None
    book_id = None
    books = show_books()

    if request.method == 'POST':
        new_name = request.form['new_name']
        book_id = int(request.form['book_id'])
        if update_book(book_id, new_name):
            flash('Книга успешно обнавлена', 'success')
        else:
            flash('Ошибка обнавления книги', 'error')
    return render_template('update_book.html', book_id=book_id, new_name=new_name, books=books)


@books_b.route('/delete_book', methods=["POST", "GET"])
def f_delete_book():
    book_id = None
    books = show_books()

    if request.method == 'POST':
        book_id = int(request.form['book_id'])
        if delete_book(book_id):
            flash('Книга успешно удалена', 'success')
        else:
            flash('Ошибка удаления книги', 'error')
    return render_template('delete_book.html', book_id=book_id, books=books)


@books_b.route('/find_book',  methods=["POST", "GET"])
def f_find_book():
    books = []
    if request.method == 'POST':
        name = request.form['name']
        books = find_book(name)
    return render_template('search.html', books=books)


@books_b.route('/my_books')
@login_required
def f_show_my_books():
    books = show_my_books()
    return render_template('my_books.html', books=books)


@books_b.route('/add_my_book/<int:book_id>')
@login_required
def f_add_my_book(book_id):
    add_my_book(current_user.id, book_id)
    return redirect(url_for('books.f_show_my_books'))



@books_b.route('/delete_my_book/<int:book_id>')
@login_required
def f_delete_my_book(book_id):
    deleted = delete_my_book(current_user.id, book_id)
    if deleted:
        updated_books = show_my_books()
        return render_template('my_books.html', books=updated_books)

DZ_L18/books/templates/add_book.html
{% extends 'index.html' %}

{% block content %}
{% if get_flashed_messages() %}
    {% for message in get_flashed_messages() %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
<div class="container mt-4">
    <div class="list-item-container alert alert-light" role="alert">
        <div class="text-center mb-4">
            <h2>Добавление книги</h2>
            <form action="{{ url_for('books.f_add_book') }}" method="post" class="mt-3">
                <div class="mb-3">
                    <label for="name" class="form-label">Название книги:</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="Введите название книги" required>
                </div>

                <div class="mb-3">
                    <label for="author_id" class="form-label">ID автора:</label>
                    <input type="number" class="form-control" id="author_id" name="author_id" placeholder="Введите ID автора" required>
                </div>

                <button type="submit" class="btn btn-primary">Добавить книгу</button>
            </form>

            <div class="mb-3">
                <label class="form-label">Авторы:</label>
                <ul class="list-group">
                    {% for author in authors %}
                        <li class="list-group-item">>{{ author.id }} - {{ author.name }}</li>
                    {% endfor %}
                </ul>
                <a href="{{ url_for('books.books') }}" class="btn btn-secondary mt-3">Назад</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

DZ_L18/books/templates/books.html
{% extends 'index.html' %}


{% block content %}
<div class="container mt-5">
    <div class="list-item-container alert alert-secondary" role="alert">
        <div class="text-center mb-4">
            <form action="{{ url_for('books.f_show_books') }}" method="get" class="mb-3">
                <button type="submit" class="btn btn-outline-dark">Показать книги</button>
            </form>

            <form action="{{ url_for('books.f_add_book') }}" method="get" class="mb-3">
                <button type="submit" class="btn btn-outline-dark">Добавить книгу</button>
            </form>

            <form action="{{ url_for('books.f_update_book') }}" method="get" class="mb-3">
                <button type="submit" class="btn btn-outline-dark">Обновить книгу</button>
            </form>

            <form action="{{ url_for('books.f_delete_book') }}" method="get" class="mb-3">
                <button type="submit" class="btn btn-outline-dark">Удалить книгу</button>
            </form>

            <form action="{{ url_for('books.f_find_book') }}" method="get" class="mb-3">
                <button type="submit" class="btn btn-outline-dark">Найти книгу</button>
            </form>

            <form action="{{ url_for('books.f_show_my_books') }}" method="get" class="mb-3">
                <button type="submit" class="btn btn-outline-dark">Избранное</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

DZ_L18/books/templates/delete_book.html
{% extends 'index.html' %}

{% block content %}
{% if get_flashed_messages() %}
    {% for message in get_flashed_messages() %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
<div class="container mt-4">
    <div class="list-item-container alert alert-light" role="alert">
        <div class="text-center mb-4">
            <h2>Удаление книги</h2>
                <form action="{{ url_for('books.f_delete_book') }}" method="post">
                    <div class="mb-3">
                        <label for="book_id" class="form-label">Выберите книгу:</label>
                        <select name="book_id" id="book_id" class="form-select">
                            <option value="">Выбрать книгу</option>
                            {% for book in books %}
                                <option value="{{ book.id }}">{{ book.id }} - {{ book.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary">Удалить книгу</button>
                </form>
                <a href="{{ url_for('books.books') }}" class="btn btn-secondary mt-3">Назад</a>
        </div>
    </div>
</div>
{% endblock %}

DZ_L18/books/templates/my_books.html
{% extends 'index.html' %}

{% block content %}
<div class="container mt-4">
    <h1 class="text-center mb-4">Список моих книг</h1>
        <div class="list-item-container text-center mb-4">
            {% if books %}
                <ul class="list-group">
                    {% for book in books %}
                        <li class="list-group-item">
                            {{ book.book.name }} - {{ book.book.author.name }}
                            <a href="{{ url_for('books.f_delete_my_book', book_id=book.id) }}">
                                <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close">
                                </button>
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p class="alert alert-warning" role="alert">Книги не найдены.</p>
            {% endif %}
            <a href="{{ url_for('books.books') }}" class="btn btn-secondary mt-3">Назад</a>
        </div>

</div>
{% endblock %}

DZ_L18/books/templates/search.html
{% extends 'index.html' %}

{% block content %}
<div class="container mt-4">
    <div class="list-item-container alert alert-light" role="alert">
        <div class="text-center mb-4">
            <h2>Поиск книги</h2>
                <form action="{{ url_for('books.f_find_book') }}" method="post" class="mt-3">
                    <div class="mb-3">
                        <label for="name" class="form-label">Название книги:</label>
                        <input type="text" class="form-control" id="name" name="name"
                               placeholder="Введите Название книги" required>
                    </div>
                    <button type="submit" class="btn btn-primary">Поиск книги</button>
                </form>
                <a href="{{ url_for('books.books') }}" class="btn btn-secondary mt-3">Назад</a>

                {% if books %}
                    <h3 class="mt-4">Результаты поиска:</h3>
                    <ul>
                    {% for book in books %}
                        <li class="list-group-item">{{ book.name }} - {{ book.author.name }}</li>
                    {% endfor %}
                    </ul>
                {% endif %}
        </div>
    </div>
</div>
{% endblock %}

DZ_L18/books/templates/show_book.html
{% extends 'index.html' %}

{% block content %}
<div class="container mt-4">
    <div class="list-item-container alert alert-info" role="alert">
        <div class="text-center mb-4">
            <h2>{{ book.name }}</h2>
            <p>Автор: {{ book.author.name }}</p>
        </div>
    </div>
    <div class="d-flex justify-content-center mb-4">
        {% if prev_book_id %}
            <a href="{{ url_for('books.f_show_book', book_id=prev_book_id) }}" class="btn btn-primary me-2 mt-3">Предыдущая книга</a>
        {% endif %}
        {% if next_book_id %}
            <a href="{{ url_for('books.f_show_book', book_id=next_book_id) }}" class="btn btn-primary me-2 mt-3">Следующая книга</a>
        {% endif %}
    </div>
    <div class="d-flex justify-content-center">
        <a href="{{ url_for('books.f_show_books') }}" class="btn btn-secondary mt-auto">Назад</a>
    </div>
</div>
{% endblock %}

DZ_L18/books/templates/show_books.html
{% extends 'index.html' %}

{% block content %}
    <style>
    .favorite-star {
        float: right; /* Выравнивает звездочку по правому краю */
        align-items: center; /* Выравнивает элементы по центру по вертикали */
    }

    </style>
<div class="container mt-4">
    <h1 class="text-center mb-4">Список книг</h1>
        <div class="list-item-container text-center mb-4">
            {% if books %}
                <ul class="list-group">
                    {% for book in books %}
                        <li class="ist-group-item d-flex align-items-center">
                            <a href="{{ url_for('books.f_show_book', book_id=book.id) }}"
                               class="list-group-item list-group-item-action" style="color: black;">
                                {{ book.name }} - {{ book.author.name }}
                            </a>
                            <a href="{{ url_for('books.f_add_my_book', book_id=book.id) }}" class="favorite-star">
                                <i class="far fa-star"></i>
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p class="alert alert-warning" role="alert">Книги не найдены.</p>
            {% endif %}
            <a href="{{ url_for('books.books') }}" class="btn btn-secondary mt-3">Назад</a>
        </div>

</div>
{% endblock %}

DZ_L18/books/templates/update_book.html
{% extends 'index.html' %}

{% block content %}
{% if get_flashed_messages() %}
    {% for message in get_flashed_messages() %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
<div class="container mt-4">
    <div class="list-item-container alert alert-light" role="alert">
        <div class="text-center mb-4">
            <h2>Обновление книги</h2>
                <form action="{{ url_for('books.f_update_book') }}" method="post">
                    <div class="mb-3">
                        <label for="new_name" class="form-label">Новое название книги:</label>
                        <input type="text" class="form-control" id="new_name" name="new_name" placeholder="Введите новое название книги" required>
                    </div>

                    <div class="mb-3">
                        <label for="book_id" class="form-label">Выберите книгу:</label>
                        <select name="book_id" id="book_id" class="form-select">
                            <option value="">Выбрать книгу</option>
                            {% for book in books %}
                                <option value="{{ book.id }}">{{ book.id }} - {{ book.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary">Обновить название</button>
                </form>
                <a href="{{ url_for('books.books') }}" class="btn btn-secondary mt-3">Назад</a>
        </div>
    </div>
</div>
{% endblock %}