DZ_L18/authors/__init__.py
from flask import Blueprint

authors_b = Blueprint('authors', __name__, template_folder="templates")

from authors.routes import *

DZ_L18/authors/routes.py
from authors import authors_b
from authors.func_bd import show_authors, add_author, delete_author
from flask import render_template, request, flash


@authors_b.route('/authors')
def authors():
    return render_template('authors.html')


@authors_b.route('/show_authors')
def f_show_authors():
    authors = show_authors()
    return render_template('show_authors.html', authors=authors)


@authors_b.route('/add_author', methods=["POST", "GET"])
def f_add_author():
    name = None

    if request.method == 'POST':
        name = request.form['name']
        if name:
            add_author(name)
            flash('Автор успешно добавлен', 'success')
        else:
            flash('Ошибка добавления автора. Проверьте данные.', 'error')
    return render_template('add_author.html', name=name)


@authors_b.route('/delete_author', methods=["POST", "GET"])
def f_delete_author():
    author_id = None
    authors = show_authors()

    if request.method == 'POST':
        author_id = int(request.form['author_id'])
        if delete_author(author_id):
            flash('Автор успешно удален', 'success')
        else:
            flash('Ошибка удаления автора', 'error')
    return render_template('delete_author.html', author_id=author_id, authors=authors)

DZ_L18/authors/templates/add_author.html
{% extends 'index.html' %}

{% block content %}
{% if get_flashed_messages() %}
    {% for message in get_flashed_messages() %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
<div class="container mt-4">
    <div class="list-item-container alert alert-light" role="alert">
        <div class="text-center mb-4">
            <h2>Добавление автора</h2>
                <form action="{{ url_for('authors.f_add_author') }}" method="post" class="mt-3">
                    <div class="mb-3">
                        <label for="name" class="form-label">Имя автора:</label>
                        <input type="text" class="form-control" id="name" name="name"
                               placeholder="Введите имя автора" required>
                    </div>
                    <button type="submit" class="btn btn-primary">Добавить автора</button>
                </form>
                <a href="{{ url_for('authors.authors') }}" class="btn btn-secondary mt-3">Назад</a>
        </div>
    </div>
</div>
{% endblock %}

DZ_L18/authors/templates/authors.html
{% extends 'index.html' %}


{% block content %}
<div class="container mt-5">
    <div class="list-item-container alert alert-secondary" role="alert">
        <div class="text-center mb-4">
            <form action="{{ url_for('authors.f_show_authors') }}" method="get" class="mb-3">
                <button type="submit" class="btn btn-secondary">Показать авторов</button>
            </form>

            <form action="{{ url_for('authors.f_add_author') }}" method="get" class="mb-3">
                <button type="submit" class="btn btn-secondary">Добавить автора</button>
            </form>

            <form action="{{ url_for('authors.f_delete_author') }}" method="get" class="mb-3">
                <button type="submit" class="btn btn-secondary">Удалить автора</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

DZ_L18/authors/templates/delete_author.html
{% extends 'index.html' %}

{% block content %}
{% if get_flashed_messages() %}
    {% for message in get_flashed_messages() %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
<div class="container mt-4">
    <div class="list-item-container alert alert-light" role="alert">
        <div class="text-center mb-4">
            <h2>Удаление автора</h2>
                <form action="{{ url_for('authors.f_delete_author') }}" method="post">
                    <div class="mb-3">
                        <label for="author_id" class="form-label">Выберите автора:</label>
                        <select name="author_id" id="author_id" class="form-select">
                            <option value="">Выбрать автора</option>
                            {% for author in authors %}
                                <option value="{{ author.id }}">{{ author.id }} - {{ author.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary">Удалить</button>
                </form>
                <a href="{{ url_for('authors.authors') }}" class="btn btn-secondary mt-3">Назад</a>
        </div>
    </div>
</div>
{% endblock %}

DZ_L18/authors/templates/show_authors.html
{% extends 'index.html' %}

{% block content %}
<div class="container mt-4">
    <h1 class="text-center mb-4">Список авторов</h1>
        <div class="list-item-container text-center mb-4">
            {% if authors %}
                <ul class="list-group">
                    {% for author in authors %}
                        <li class="list-group-item">{{ author.name }}</li>
                    {% endfor %}
                </ul>
            {% else %}
                <p class="alert alert-warning" role="alert">Авторы не найдены.</p>
            {% endif %}
            <a href="{{ url_for('authors.authors') }}" class="btn btn-secondary mt-3">Назад</a>
        </div>
</div>
{% endblock %}